name: Waka Readme

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anuraghazra/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIME_RANGE: "all_time"
          SHOW_OS: "true"
          SHOW_PROJECTS: "false"
          SHOW_EDITORS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_COMMIT: "false"
          SHOW_LANGUAGE_PER_REPO: "false"
          SHOW_SHORT_INFO: "false"
          SHOW_LOC_CHART: "false"